<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-IUIGTE3" ignored="2" name="Default test(failed)" tests="1" failures="1" timestamp="2021-05-22T23:16:47 IST" time="0.093" errors="0">
  <testcase name="TC2" time="0.021" classname="demo_1.FailedTestCasesExecution">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at demo_1.FailedTestCasesExecution.TC2(FailedTestCasesExecution.java:17)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase name="TC3" time="0.0" classname="demo_1.FailedTestCasesExecution">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase name="TC1" time="0.0" classname="demo_1.FailedTestCasesExecution">
    <ignored/>
  </testcase> <!-- TC1 -->
</testsuite> <!-- Default test(failed) -->
